<?php
const LOGIN_API = 'LOG001';
const REFRESH_API = "REF002";
const LOGOUT_API = "LOGO002";
const CARGO_TRANSACTION_API_CODE = "CARGTRANS003";
const TICKET_TRANSACTION_API_CODE = "TICKTRANS004";
const SUMMARY_DETAILS_API_CODE = "SUMDET005";
